[package]
name = "szyk"
license = "ISC"
version = "0.1.1"
authors = ["nm <mnkisala@gmail.com>"]
edition = "2018"
description = "generic topological sort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
